// Generated by gencpp from file beginner_tutorials/Event.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_EVENT_H
#define BEGINNER_TUTORIALS_MESSAGE_EVENT_H

#include <ros/service_traits.h>


#include <beginner_tutorials/EventRequest.h>
#include <beginner_tutorials/EventResponse.h>


namespace beginner_tutorials
{

struct Event
{

typedef EventRequest Request;
typedef EventResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Event
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::Event > {
  static const char* value()
  {
    return "868b07f2540b8f55d0a16c4ccc0407bf";
  }

  static const char* value(const ::beginner_tutorials::Event&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::Event > {
  static const char* value()
  {
    return "beginner_tutorials/Event";
  }

  static const char* value(const ::beginner_tutorials::Event&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::EventRequest> should match
// service_traits::MD5Sum< ::beginner_tutorials::Event >
template<>
struct MD5Sum< ::beginner_tutorials::EventRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::Event >::value();
  }
  static const char* value(const ::beginner_tutorials::EventRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::EventRequest> should match
// service_traits::DataType< ::beginner_tutorials::Event >
template<>
struct DataType< ::beginner_tutorials::EventRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::Event >::value();
  }
  static const char* value(const ::beginner_tutorials::EventRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::EventResponse> should match
// service_traits::MD5Sum< ::beginner_tutorials::Event >
template<>
struct MD5Sum< ::beginner_tutorials::EventResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::Event >::value();
  }
  static const char* value(const ::beginner_tutorials::EventResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::EventResponse> should match
// service_traits::DataType< ::beginner_tutorials::Event >
template<>
struct DataType< ::beginner_tutorials::EventResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::Event >::value();
  }
  static const char* value(const ::beginner_tutorials::EventResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_EVENT_H
