// Generated by gencpp from file conv/convResponse.msg
// DO NOT EDIT!


#ifndef CONV_MESSAGE_CONVRESPONSE_H
#define CONV_MESSAGE_CONVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace conv
{
template <class ContainerAllocator>
struct convResponse_
{
  typedef convResponse_<ContainerAllocator> Type;

  convResponse_()
    : result()  {
    }
  convResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::conv::convResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::conv::convResponse_<ContainerAllocator> const> ConstPtr;

}; // struct convResponse_

typedef ::conv::convResponse_<std::allocator<void> > convResponse;

typedef boost::shared_ptr< ::conv::convResponse > convResponsePtr;
typedef boost::shared_ptr< ::conv::convResponse const> convResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::conv::convResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::conv::convResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::conv::convResponse_<ContainerAllocator1> & lhs, const ::conv::convResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::conv::convResponse_<ContainerAllocator1> & lhs, const ::conv::convResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace conv

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::conv::convResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::conv::convResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::conv::convResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::conv::convResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::conv::convResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::conv::convResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::conv::convResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b7ed20811caa3db643b4512e66e3f767";
  }

  static const char* value(const ::conv::convResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb7ed20811caa3db6ULL;
  static const uint64_t static_value2 = 0x43b4512e66e3f767ULL;
};

template<class ContainerAllocator>
struct DataType< ::conv::convResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "conv/convResponse";
  }

  static const char* value(const ::conv::convResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::conv::convResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[] result\n"
;
  }

  static const char* value(const ::conv::convResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::conv::convResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct convResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::conv::convResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::conv::convResponse_<ContainerAllocator>& v)
  {
    s << indent << "result[]" << std::endl;
    for (size_t i = 0; i < v.result.size(); ++i)
    {
      s << indent << "  result[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.result[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONV_MESSAGE_CONVRESPONSE_H
