// Generated by gencpp from file conv/conv.msg
// DO NOT EDIT!


#ifndef CONV_MESSAGE_CONV_H
#define CONV_MESSAGE_CONV_H

#include <ros/service_traits.h>


#include <conv/convRequest.h>
#include <conv/convResponse.h>


namespace conv
{

struct conv
{

typedef convRequest Request;
typedef convResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct conv
} // namespace conv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::conv::conv > {
  static const char* value()
  {
    return "fd95d1cd8607c017d163c5f38defaa91";
  }

  static const char* value(const ::conv::conv&) { return value(); }
};

template<>
struct DataType< ::conv::conv > {
  static const char* value()
  {
    return "conv/conv";
  }

  static const char* value(const ::conv::conv&) { return value(); }
};


// service_traits::MD5Sum< ::conv::convRequest> should match
// service_traits::MD5Sum< ::conv::conv >
template<>
struct MD5Sum< ::conv::convRequest>
{
  static const char* value()
  {
    return MD5Sum< ::conv::conv >::value();
  }
  static const char* value(const ::conv::convRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::conv::convRequest> should match
// service_traits::DataType< ::conv::conv >
template<>
struct DataType< ::conv::convRequest>
{
  static const char* value()
  {
    return DataType< ::conv::conv >::value();
  }
  static const char* value(const ::conv::convRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::conv::convResponse> should match
// service_traits::MD5Sum< ::conv::conv >
template<>
struct MD5Sum< ::conv::convResponse>
{
  static const char* value()
  {
    return MD5Sum< ::conv::conv >::value();
  }
  static const char* value(const ::conv::convResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::conv::convResponse> should match
// service_traits::DataType< ::conv::conv >
template<>
struct DataType< ::conv::convResponse>
{
  static const char* value()
  {
    return DataType< ::conv::conv >::value();
  }
  static const char* value(const ::conv::convResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONV_MESSAGE_CONV_H
